;; This code was automatically generated by the 'metav' library.
(ns rccst.version)

(def module-name "rccst")
(def path ".")
(def version "0.7.1-0x6eb2")
(def tag "v0.7.1-0x6eb2")
(def generated-at "2022-07-07T19:31:39Z")





