(ns bh.rccst.api.version
  (:require [clojure.tools.logging :as log]
            [compojure.api.sweet :as sweet]
            [schema.core :as s]

            [bh.rccst.api.common :as c]
            [bh.rccst.version :as v]))


(s/defschema VersionResponse
  {:version s/Str
   :build-date s/Str})


(defn- get-version
  "returns the version number, as generated by the Metav tool.

  returns: [[VersionResponse]]

  > See also:
  >
  > [Metav](https://github.com/jgrodziski/metav)
  "

  []
  (log/info "get-version")
  {:version v/version :build-date v/generated-at})


(def version-handler
  "handler for `/version` URL

  > See also:
  >
  > [Compojure](https://github.com/weavejester/compojure)
  > [compojure.sweet](https://github.com/metosin/compojure-api)
  "
  (sweet/GET "/version" _
    :return VersionResponse
    :summary "get the version number from the server"
    (c/wrapper (#'get-version))))


; test schema
(comment
  (s/validate VersionResponse (get-version))
  (s/validate VersionResponse {})
  (s/validate VersionResponse nil)

  ())