apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\j68916\Documents\octools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: rccst-postgres
  name: rccst-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rccst-postgres
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\j68916\Documents\octools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        app: rccst-postgres
    spec:
      containers:
        - name: rccst-postgres
          image: docker-ng-staging.ms.northgrum.com/paas/customerbase/segs:rccst-postgres-1.0.2
          env:
            - name: POSTGRES_USER
              value: "1001710000"
            - name: POSTGRES_PASSWORD
              value: Password
            - name: POSTGRES_DB
              value: rccst
          ports:
            - containerPort: 5432
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
    strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rccst-postgres
  namespace: segs-sandbox
  labels:
    app: rccst-postgres
spec:
  selector:
    app: rccst-postgres
  ports:
    - protocol: TCP
      port: 5432
